// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestCases.FeaturesAndSteps
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("DoublyString", Description="\tNumber of eggs and number of floors are given.", SourceFile="FeaturesAndSteps\\DoublyString.feature", SourceLine=0)]
    public partial class DoublyStringFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "DoublyString.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "DoublyString", "\tNumber of eggs and number of floors are given.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void DoublyStringTestCases(string @string, string isDoublyString, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "NormalSolution"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("DoublyString test cases", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given(string.Format("DoublyString input {0}", @string), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.Then(string.Format("DoublyString result should be {0}", isDoublyString), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 0", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant0()
        {
            this.DoublyStringTestCases("a", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 1", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant1()
        {
            this.DoublyStringTestCases("aa", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 2", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant2()
        {
            this.DoublyStringTestCases("abcabc", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 3", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant3()
        {
            this.DoublyStringTestCases("abcdabcd", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 4", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant4()
        {
            this.DoublyStringTestCases("Xabcdabcd", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 5", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant5()
        {
            this.DoublyStringTestCases("aXbcdabcd", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 6", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant6()
        {
            this.DoublyStringTestCases("abXcdabcd", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 7", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant7()
        {
            this.DoublyStringTestCases("abcXdabcd", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 8", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant8()
        {
            this.DoublyStringTestCases("abcdXabcd", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 9", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant9()
        {
            this.DoublyStringTestCases("abcdaXbcd", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 10", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant10()
        {
            this.DoublyStringTestCases("abcdabXcd", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 11", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant11()
        {
            this.DoublyStringTestCases("abcdabcXd", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 12", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant12()
        {
            this.DoublyStringTestCases("XabcXdabcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 13", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant13()
        {
            this.DoublyStringTestCases("aXbcdXabcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 14", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant14()
        {
            this.DoublyStringTestCases("abXcdaXbcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 15", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant15()
        {
            this.DoublyStringTestCases("abcXXdabcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 16", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant16()
        {
            this.DoublyStringTestCases("abcdXaXbcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 17", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant17()
        {
            this.DoublyStringTestCases("abXcdaXbcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 18", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant18()
        {
            this.DoublyStringTestCases("abcXdabXcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 19", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant19()
        {
            this.DoublyStringTestCases("abcXdabcXd", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 20", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant20()
        {
            this.DoublyStringTestCases("XabcXdabcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 21", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant21()
        {
            this.DoublyStringTestCases("aXbcdXabYcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 22", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant22()
        {
            this.DoublyStringTestCases("abXcYdaXbcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 23", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant23()
        {
            this.DoublyStringTestCases("abcXXdabYcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 24", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant24()
        {
            this.DoublyStringTestCases("abYcdXaXbcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 25", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant25()
        {
            this.DoublyStringTestCases("abXYcdaXbcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 26", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant26()
        {
            this.DoublyStringTestCases("abcXdaYbXcd", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("DoublyString test cases, Variant 27", new string[] {
                "NormalSolution"}, SourceLine=10)]
        public virtual void DoublyStringTestCases_Variant27()
        {
            this.DoublyStringTestCases("aYbcXdabcXd", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
