// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestCases.FeaturesAndSteps
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("LongestCommonSubSequence", Description="Two strings are given, we need to find LongestCommonSubSequence.", SourceFile="FeaturesAndSteps\\LongestCommonSubSequence.feature", SourceLine=0)]
    public partial class LongestCommonSubSequenceFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "LongestCommonSubSequence.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "LongestCommonSubSequence", "Two strings are given, we need to find LongestCommonSubSequence.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SomeScenariosOfInputsForBottomUpApproach(string string1, string string2, string subSequence, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DynamicProgrammingBottomUp"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Some scenarios of inputs for bottom up approach", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given(string.Format("input of LongestCommonSubSequence {0}, {1}", string1, string2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.Then(string.Format("the LongestCommonSubSequence should be {0}", subSequence), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 0", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant0()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("a", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 1", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant1()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("ab", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 2", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant2()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("abc", "1ab23c45", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 3", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant3()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("abc", "1abc23ab4abcd5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 4", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant4()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("abc", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 5", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant5()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("abcd", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 6", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant6()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xa", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 7", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant7()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xab", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 8", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant8()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabc", "1ab23c45", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 9", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant9()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabc", "1abc23ab4abcd5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 10", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant10()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabc", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 11", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant11()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabcd", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 12", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant12()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xaxa", "1a23a4a5", "aa", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 13", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant13()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabxab", "1a23a4a5", "aa", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 14", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant14()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabcxabc", "1ab23c45", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 15", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant15()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabcxabc", "1abc23ab4abcd5", "abcabc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 16", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant16()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabcxabc", "1abc2abc34abc5", "abcabc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 17", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant17()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabcdxabcd", "1abc2abc34abc5", "abcabc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 18", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant18()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("aa", "1a23a4a5", "aa", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 19", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant19()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("ab", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 20", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant20()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("abc", "1ab23c45", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 21", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant21()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("axbycd", "1abc23ab4abc5d", "abcd", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 22", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant22()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("a#b#c", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 23", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant23()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("#a#b#c#d#", "1abc2abc34abc5d", "abcd", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
