// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestCases.FeaturesAndSteps
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("LongestCommonSubString", Description="Two strings are given, we need to find longest common substring.", SourceFile="FeaturesAndSteps\\LongestCommonSubString.feature", SourceLine=0)]
    public partial class LongestCommonSubStringFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "LongestCommonSubString.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "LongestCommonSubString", "Two strings are given, we need to find longest common substring.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SomeScenariosOfInputsForTopDoneApproach(string string1, string string2, string subString, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DynamicProgrammingTopDown"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Some scenarios of inputs for top done approach", @__tags);
#line 5
this.ScenarioSetup(scenarioInfo);
#line 6
 testRunner.Given(string.Format("two strings {0}, {1}", string1, string2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 7
 testRunner.Then(string.Format("the longest common substring should be {0}", subString), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 0", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant0()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("a", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 1", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant1()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("ab", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 2", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant2()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("abc", "1ab23c45", "ab", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 3", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant3()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("abc", "1abc23ab4abcd5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 4", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant4()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("abc", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 5", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant5()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("abcd", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 6", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant6()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("xa", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 7", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant7()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("xab", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 8", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant8()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("xabc", "1ab23c45", "ab", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 9", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant9()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("xabc", "1abc23ab4abcd5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 10", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant10()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("xabc", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 11", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant11()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("xabcd", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 12", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant12()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("xaxa", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 13", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant13()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("xabxab", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 14", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant14()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("xabcxabc", "1ab23c45", "ab", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 15", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant15()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("xabcxabc", "1abc23ab4abcd5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 16", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant16()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("xabcxabc", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for top done approach, Variant 17", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=10)]
        public virtual void SomeScenariosOfInputsForTopDoneApproach_Variant17()
        {
            this.SomeScenariosOfInputsForTopDoneApproach("xabcdxabcd", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        public virtual void SomeScenariosOfInputsForBottomUpApproach(string string1, string string2, string subString, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DynamicProgrammingBottomUp"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Some scenarios of inputs for bottom up approach", @__tags);
#line 33
this.ScenarioSetup(scenarioInfo);
#line 34
 testRunner.Given(string.Format("two strings {0}, {1}", string1, string2), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 35
 testRunner.Then(string.Format("the longest common substring should be {0}", subString), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 0", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant0()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("a", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 1", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant1()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("ab", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 2", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant2()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("abc", "1ab23c45", "ab", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 3", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant3()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("abc", "1abc23ab4abcd5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 4", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant4()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("abc", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 5", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant5()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("abcd", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 6", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant6()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xa", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 7", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant7()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xab", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 8", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant8()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabc", "1ab23c45", "ab", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 9", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant9()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabc", "1abc23ab4abcd5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 10", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant10()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabc", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 11", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant11()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabcd", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 12", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant12()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xaxa", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 13", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant13()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabxab", "1a23a4a5", "a", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 14", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant14()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabcxabc", "1ab23c45", "ab", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 15", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant15()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabcxabc", "1abc23ab4abcd5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 16", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant16()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabcxabc", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Some scenarios of inputs for bottom up approach, Variant 17", new string[] {
                "DynamicProgrammingBottomUp"}, SourceLine=38)]
        public virtual void SomeScenariosOfInputsForBottomUpApproach_Variant17()
        {
            this.SomeScenariosOfInputsForBottomUpApproach("xabcdxabcd", "1abc2abc34abc5", "abc", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
