// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestCases.FeaturesAndSteps
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("MinimumNumberOfJumps", SourceFile="FeaturesAndSteps\\MinimumNumberOfJumps.feature", SourceLine=0)]
    public partial class MinimumNumberOfJumpsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "MinimumNumberOfJumps.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "MinimumNumberOfJumps", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void MinimumNumberOfJumpsTesting(string sequence, string jumps, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DynamicProgrammingTopDown"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("MinimumNumberOfJumps Testing", @__tags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("MinimumNumberOfJumps sequence {0}", sequence), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.Then(string.Format("MinimumNumberOfJumps solution should be {0}", jumps), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("MinimumNumberOfJumps Testing, 1, 3, 5, 8, 9, 2, 6, 7, 6, 8, 9", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=9)]
        public virtual void MinimumNumberOfJumpsTesting_13589267689()
        {
            this.MinimumNumberOfJumpsTesting("1, 3, 5, 8, 9, 2, 6, 7, 6, 8, 9", "3", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("MinimumNumberOfJumps Testing, 1, 3, 5, 8, 0, 2, 6, 7, 6, 8, 9", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=9)]
        public virtual void MinimumNumberOfJumpsTesting_13580267689()
        {
            this.MinimumNumberOfJumpsTesting("1, 3, 5, 8, 0, 2, 6, 7, 6, 8, 9", "3", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("MinimumNumberOfJumps Testing, 1, 3, 5, 0, 0, 2, 6, 7, 6, 8, 9", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=9)]
        public virtual void MinimumNumberOfJumpsTesting_13500267689()
        {
            this.MinimumNumberOfJumpsTesting("1, 3, 5, 0, 0, 2, 6, 7, 6, 8, 9", "4", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
