// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestCases.FeaturesAndSteps
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("PartitionProblem", SourceFile="FeaturesAndSteps\\PartitionProblem.feature", SourceLine=0)]
    public partial class PartitionProblemFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "PartitionProblem.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "PartitionProblem", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void PallondromPartitioningTesting(string set, string canBePartitioned, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DynamicProgrammingTopDown"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("PallondromPartitioning Testing", @__tags);
#line 4
this.ScenarioSetup(scenarioInfo);
#line 5
 testRunner.Given(string.Format("PartitionProblem input {0}", set), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
 testRunner.Then(string.Format("PartitionProblem solution should be {0}", canBePartitioned), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("PallondromPartitioning Testing, 0", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=9)]
        public virtual void PallondromPartitioningTesting_0()
        {
            this.PallondromPartitioningTesting("0", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("PallondromPartitioning Testing, 1", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=9)]
        public virtual void PallondromPartitioningTesting_1()
        {
            this.PallondromPartitioningTesting("1", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("PallondromPartitioning Testing, 2", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=9)]
        public virtual void PallondromPartitioningTesting_2()
        {
            this.PallondromPartitioningTesting("2", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("PallondromPartitioning Testing, 1,2", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=9)]
        public virtual void PallondromPartitioningTesting_12()
        {
            this.PallondromPartitioningTesting("1,2", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("PallondromPartitioning Testing, 1,2,3", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=9)]
        public virtual void PallondromPartitioningTesting_123()
        {
            this.PallondromPartitioningTesting("1,2,3", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("PallondromPartitioning Testing, 1,2,3,4", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=9)]
        public virtual void PallondromPartitioningTesting_1234()
        {
            this.PallondromPartitioningTesting("1,2,3,4", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("PallondromPartitioning Testing, 9,8,1,2,0", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=9)]
        public virtual void PallondromPartitioningTesting_98120()
        {
            this.PallondromPartitioningTesting("9,8,1,2,0", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("PallondromPartitioning Testing, 1,5,11,5", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=9)]
        public virtual void PallondromPartitioningTesting_15115()
        {
            this.PallondromPartitioningTesting("1,5,11,5", "true", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("PallondromPartitioning Testing, 1,5,3", new string[] {
                "DynamicProgrammingTopDown"}, SourceLine=9)]
        public virtual void PallondromPartitioningTesting_153()
        {
            this.PallondromPartitioningTesting("1,5,3", "false", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
